# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuditRecords(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'limit': 'int',
        'offset': 'int',
        'records': 'list[AuditRecordBean]',
        'total': 'int'
    }

    attribute_map = {
        'limit': 'limit',
        'offset': 'offset',
        'records': 'records',
        'total': 'total'
    }

    def __init__(self, limit=None, offset=None, records=None, total=None):  # noqa: E501
        """AuditRecords - a model defined in Swagger"""  # noqa: E501
        self._limit = None
        self._offset = None
        self._records = None
        self._total = None
        self.discriminator = None
        if limit is not None:
            self.limit = limit
        if offset is not None:
            self.offset = offset
        if records is not None:
            self.records = records
        if total is not None:
            self.total = total

    @property
    def limit(self):
        """Gets the limit of this AuditRecords.  # noqa: E501

        The requested or default limit on the number of audit items to be returned.  # noqa: E501

        :return: The limit of this AuditRecords.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this AuditRecords.

        The requested or default limit on the number of audit items to be returned.  # noqa: E501

        :param limit: The limit of this AuditRecords.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this AuditRecords.  # noqa: E501

        The number of audit items skipped before the first item in this list.  # noqa: E501

        :return: The offset of this AuditRecords.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this AuditRecords.

        The number of audit items skipped before the first item in this list.  # noqa: E501

        :param offset: The offset of this AuditRecords.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def records(self):
        """Gets the records of this AuditRecords.  # noqa: E501

        The list of audit items.  # noqa: E501

        :return: The records of this AuditRecords.  # noqa: E501
        :rtype: list[AuditRecordBean]
        """
        return self._records

    @records.setter
    def records(self, records):
        """Sets the records of this AuditRecords.

        The list of audit items.  # noqa: E501

        :param records: The records of this AuditRecords.  # noqa: E501
        :type: list[AuditRecordBean]
        """

        self._records = records

    @property
    def total(self):
        """Gets the total of this AuditRecords.  # noqa: E501

        The total number of audit items returned.  # noqa: E501

        :return: The total of this AuditRecords.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this AuditRecords.

        The total number of audit items returned.  # noqa: E501

        :param total: The total of this AuditRecords.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuditRecords, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuditRecords):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
