# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Hierarchy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_level_id': 'int',
        'levels': 'list[SimplifiedHierarchyLevel]'
    }

    attribute_map = {
        'base_level_id': 'baseLevelId',
        'levels': 'levels'
    }

    def __init__(self, base_level_id=None, levels=None):  # noqa: E501
        """Hierarchy - a model defined in Swagger"""  # noqa: E501
        self._base_level_id = None
        self._levels = None
        self.discriminator = None
        if base_level_id is not None:
            self.base_level_id = base_level_id
        if levels is not None:
            self.levels = levels

    @property
    def base_level_id(self):
        """Gets the base_level_id of this Hierarchy.  # noqa: E501

        The ID of the base level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).  # noqa: E501

        :return: The base_level_id of this Hierarchy.  # noqa: E501
        :rtype: int
        """
        return self._base_level_id

    @base_level_id.setter
    def base_level_id(self, base_level_id):
        """Sets the base_level_id of this Hierarchy.

        The ID of the base level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).  # noqa: E501

        :param base_level_id: The base_level_id of this Hierarchy.  # noqa: E501
        :type: int
        """

        self._base_level_id = base_level_id

    @property
    def levels(self):
        """Gets the levels of this Hierarchy.  # noqa: E501

        Details about the hierarchy level.  # noqa: E501

        :return: The levels of this Hierarchy.  # noqa: E501
        :rtype: list[SimplifiedHierarchyLevel]
        """
        return self._levels

    @levels.setter
    def levels(self, levels):
        """Sets the levels of this Hierarchy.

        Details about the hierarchy level.  # noqa: E501

        :param levels: The levels of this Hierarchy.  # noqa: E501
        :type: list[SimplifiedHierarchyLevel]
        """

        self._levels = levels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Hierarchy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Hierarchy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
