# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.audit_records_api import AuditRecordsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuditRecordsApi(unittest.TestCase):
    """AuditRecordsApi unit test stubs"""

    def setUp(self):
        self.api = AuditRecordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_audit_records(self):
        """Test case for get_audit_records

        Get audit records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
