# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.jira_expressions_api import JiraExpressionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJiraExpressionsApi(unittest.TestCase):
    """JiraExpressionsApi unit test stubs"""

    def setUp(self):
        self.api = JiraExpressionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analyse_expression(self):
        """Test case for analyse_expression

        Analyse Jira expression  # noqa: E501
        """
        pass

    def test_evaluate_jira_expression(self):
        """Test case for evaluate_jira_expression

        Currently being removed. Evaluate Jira expression  # noqa: E501
        """
        pass

    def test_evaluate_jsis_jira_expression(self):
        """Test case for evaluate_jsis_jira_expression

        Evaluate Jira expression using enhanced search API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
