# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issues_api import IssuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssuesApi(unittest.TestCase):
    """IssuesApi unit test stubs"""

    def setUp(self):
        self.api = IssuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_issues(self):
        """Test case for archive_issues

        Archive issue(s) by issue ID/key  # noqa: E501
        """
        pass

    def test_archive_issues_async(self):
        """Test case for archive_issues_async

        Archive issue(s) by JQL  # noqa: E501
        """
        pass

    def test_assign_issue(self):
        """Test case for assign_issue

        Assign issue  # noqa: E501
        """
        pass

    def test_bulk_fetch_issues(self):
        """Test case for bulk_fetch_issues

        Bulk fetch issues  # noqa: E501
        """
        pass

    def test_create_issue(self):
        """Test case for create_issue

        Create issue  # noqa: E501
        """
        pass

    def test_create_issues(self):
        """Test case for create_issues

        Bulk create issue  # noqa: E501
        """
        pass

    def test_delete_issue(self):
        """Test case for delete_issue

        Delete issue  # noqa: E501
        """
        pass

    def test_do_transition(self):
        """Test case for do_transition

        Transition issue  # noqa: E501
        """
        pass

    def test_edit_issue(self):
        """Test case for edit_issue

        Edit issue  # noqa: E501
        """
        pass

    def test_export_archived_issues(self):
        """Test case for export_archived_issues

        Export archived issue(s)  # noqa: E501
        """
        pass

    def test_get_bulk_changelogs(self):
        """Test case for get_bulk_changelogs

        Bulk fetch changelogs  # noqa: E501
        """
        pass

    def test_get_change_logs(self):
        """Test case for get_change_logs

        Get changelogs  # noqa: E501
        """
        pass

    def test_get_change_logs_by_ids(self):
        """Test case for get_change_logs_by_ids

        Get changelogs by IDs  # noqa: E501
        """
        pass

    def test_get_create_issue_meta(self):
        """Test case for get_create_issue_meta

        Get create issue metadata  # noqa: E501
        """
        pass

    def test_get_create_issue_meta_issue_type_id(self):
        """Test case for get_create_issue_meta_issue_type_id

        Get create field metadata for a project and issue type id  # noqa: E501
        """
        pass

    def test_get_create_issue_meta_issue_types(self):
        """Test case for get_create_issue_meta_issue_types

        Get create metadata issue types for a project  # noqa: E501
        """
        pass

    def test_get_edit_issue_meta(self):
        """Test case for get_edit_issue_meta

        Get edit issue metadata  # noqa: E501
        """
        pass

    def test_get_events(self):
        """Test case for get_events

        Get events  # noqa: E501
        """
        pass

    def test_get_issue(self):
        """Test case for get_issue

        Get issue  # noqa: E501
        """
        pass

    def test_get_issue_limit_report(self):
        """Test case for get_issue_limit_report

        Get issue limit report  # noqa: E501
        """
        pass

    def test_get_transitions(self):
        """Test case for get_transitions

        Get transitions  # noqa: E501
        """
        pass

    def test_notify(self):
        """Test case for notify

        Send notification for issue  # noqa: E501
        """
        pass

    def test_unarchive_issues(self):
        """Test case for unarchive_issues

        Unarchive issue(s) by issue keys/ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
