# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issue_watchers_api import IssueWatchersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssueWatchersApi(unittest.TestCase):
    """IssueWatchersApi unit test stubs"""

    def setUp(self):
        self.api = IssueWatchersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_watcher(self):
        """Test case for add_watcher

        Add watcher  # noqa: E501
        """
        pass

    def test_get_is_watching_issue_bulk(self):
        """Test case for get_is_watching_issue_bulk

        Get is watching issue bulk  # noqa: E501
        """
        pass

    def test_get_issue_watchers(self):
        """Test case for get_issue_watchers

        Get issue watchers  # noqa: E501
        """
        pass

    def test_remove_watcher(self):
        """Test case for remove_watcher

        Delete watcher  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
