# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.jira_multi_select_component_field import JiraMultiSelectComponentField  # noqa: E501
from swagger_client.rest import ApiException


class TestJiraMultiSelectComponentField(unittest.TestCase):
    """JiraMultiSelectComponentField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJiraMultiSelectComponentField(self):
        """Test JiraMultiSelectComponentField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jira_multi_select_component_field.JiraMultiSelectComponentField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
