# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_search_api import UserSearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserSearchApi(unittest.TestCase):
    """UserSearchApi unit test stubs"""

    def setUp(self):
        self.api = UserSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_assignable_users(self):
        """Test case for find_assignable_users

        Find users assignable to issues  # noqa: E501
        """
        pass

    def test_find_bulk_assignable_users(self):
        """Test case for find_bulk_assignable_users

        Find users assignable to projects  # noqa: E501
        """
        pass

    def test_find_user_keys_by_query(self):
        """Test case for find_user_keys_by_query

        Find user keys by query  # noqa: E501
        """
        pass

    def test_find_users(self):
        """Test case for find_users

        Find users  # noqa: E501
        """
        pass

    def test_find_users_by_query(self):
        """Test case for find_users_by_query

        Find users by query  # noqa: E501
        """
        pass

    def test_find_users_for_picker(self):
        """Test case for find_users_for_picker

        Find users for picker  # noqa: E501
        """
        pass

    def test_find_users_with_all_permissions(self):
        """Test case for find_users_with_all_permissions

        Find users with permissions  # noqa: E501
        """
        pass

    def test_find_users_with_browse_permission(self):
        """Test case for find_users_with_browse_permission

        Find users with browse permission  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
