# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.jql_api import JQLApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJQLApi(unittest.TestCase):
    """JQLApi unit test stubs"""

    def setUp(self):
        self.api = JQLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_auto_complete(self):
        """Test case for get_auto_complete

        Get field reference data (GET)  # noqa: E501
        """
        pass

    def test_get_auto_complete_post(self):
        """Test case for get_auto_complete_post

        Get field reference data (POST)  # noqa: E501
        """
        pass

    def test_get_field_auto_complete_for_query_string(self):
        """Test case for get_field_auto_complete_for_query_string

        Get field auto complete suggestions  # noqa: E501
        """
        pass

    def test_migrate_queries(self):
        """Test case for migrate_queries

        Convert user identifiers to account IDs in JQL queries  # noqa: E501
        """
        pass

    def test_parse_jql_queries(self):
        """Test case for parse_jql_queries

        Parse JQL query  # noqa: E501
        """
        pass

    def test_sanitise_jql_queries(self):
        """Test case for sanitise_jql_queries

        Sanitize JQL queries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
