# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issue_security_schemes_api import IssueSecuritySchemesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssueSecuritySchemesApi(unittest.TestCase):
    """IssueSecuritySchemesApi unit test stubs"""

    def setUp(self):
        self.api = IssueSecuritySchemesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_security_level(self):
        """Test case for add_security_level

        Add issue security levels  # noqa: E501
        """
        pass

    def test_add_security_level_members(self):
        """Test case for add_security_level_members

        Add issue security level members  # noqa: E501
        """
        pass

    def test_associate_schemes_to_projects(self):
        """Test case for associate_schemes_to_projects

        Associate security scheme to project  # noqa: E501
        """
        pass

    def test_create_issue_security_scheme(self):
        """Test case for create_issue_security_scheme

        Create issue security scheme  # noqa: E501
        """
        pass

    def test_delete_security_scheme(self):
        """Test case for delete_security_scheme

        Delete issue security scheme  # noqa: E501
        """
        pass

    def test_get_issue_security_scheme(self):
        """Test case for get_issue_security_scheme

        Get issue security scheme  # noqa: E501
        """
        pass

    def test_get_issue_security_schemes(self):
        """Test case for get_issue_security_schemes

        Get issue security schemes  # noqa: E501
        """
        pass

    def test_get_security_level_members(self):
        """Test case for get_security_level_members

        Get issue security level members  # noqa: E501
        """
        pass

    def test_get_security_levels(self):
        """Test case for get_security_levels

        Get issue security levels  # noqa: E501
        """
        pass

    def test_remove_level(self):
        """Test case for remove_level

        Remove issue security level  # noqa: E501
        """
        pass

    def test_remove_member_from_security_level(self):
        """Test case for remove_member_from_security_level

        Remove member from issue security level  # noqa: E501
        """
        pass

    def test_search_projects_using_security_schemes(self):
        """Test case for search_projects_using_security_schemes

        Get projects using issue security schemes  # noqa: E501
        """
        pass

    def test_search_security_schemes(self):
        """Test case for search_security_schemes

        Search issue security schemes  # noqa: E501
        """
        pass

    def test_set_default_levels(self):
        """Test case for set_default_levels

        Set default issue security levels  # noqa: E501
        """
        pass

    def test_update_issue_security_scheme(self):
        """Test case for update_issue_security_scheme

        Update issue security scheme  # noqa: E501
        """
        pass

    def test_update_security_level(self):
        """Test case for update_security_level

        Update issue security level  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
