# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.server_info_api import ServerInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServerInfoApi(unittest.TestCase):
    """ServerInfoApi unit test stubs"""

    def setUp(self):
        self.api = ServerInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_server_info(self):
        """Test case for get_server_info

        Get Jira instance info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
