# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issue_comments_api import IssueCommentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssueCommentsApi(unittest.TestCase):
    """IssueCommentsApi unit test stubs"""

    def setUp(self):
        self.api = IssueCommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_comment(self):
        """Test case for add_comment

        Add comment  # noqa: E501
        """
        pass

    def test_delete_comment(self):
        """Test case for delete_comment

        Delete comment  # noqa: E501
        """
        pass

    def test_get_comment(self):
        """Test case for get_comment

        Get comment  # noqa: E501
        """
        pass

    def test_get_comments(self):
        """Test case for get_comments

        Get comments  # noqa: E501
        """
        pass

    def test_get_comments_by_ids(self):
        """Test case for get_comments_by_ids

        Get comments by IDs  # noqa: E501
        """
        pass

    def test_update_comment(self):
        """Test case for update_comment

        Update comment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
