# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BulkTransitionGetAvailableTransitions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'available_transitions': 'list[IssueBulkTransitionForWorkflow]',
        'ending_before': 'str',
        'starting_after': 'str'
    }

    attribute_map = {
        'available_transitions': 'availableTransitions',
        'ending_before': 'endingBefore',
        'starting_after': 'startingAfter'
    }

    def __init__(self, available_transitions=None, ending_before=None, starting_after=None):  # noqa: E501
        """BulkTransitionGetAvailableTransitions - a model defined in Swagger"""  # noqa: E501
        self._available_transitions = None
        self._ending_before = None
        self._starting_after = None
        self.discriminator = None
        if available_transitions is not None:
            self.available_transitions = available_transitions
        if ending_before is not None:
            self.ending_before = ending_before
        if starting_after is not None:
            self.starting_after = starting_after

    @property
    def available_transitions(self):
        """Gets the available_transitions of this BulkTransitionGetAvailableTransitions.  # noqa: E501

        List of available transitions for bulk transition operation for requested issues grouped by workflow  # noqa: E501

        :return: The available_transitions of this BulkTransitionGetAvailableTransitions.  # noqa: E501
        :rtype: list[IssueBulkTransitionForWorkflow]
        """
        return self._available_transitions

    @available_transitions.setter
    def available_transitions(self, available_transitions):
        """Sets the available_transitions of this BulkTransitionGetAvailableTransitions.

        List of available transitions for bulk transition operation for requested issues grouped by workflow  # noqa: E501

        :param available_transitions: The available_transitions of this BulkTransitionGetAvailableTransitions.  # noqa: E501
        :type: list[IssueBulkTransitionForWorkflow]
        """

        self._available_transitions = available_transitions

    @property
    def ending_before(self):
        """Gets the ending_before of this BulkTransitionGetAvailableTransitions.  # noqa: E501

        The end cursor for use in pagination.  # noqa: E501

        :return: The ending_before of this BulkTransitionGetAvailableTransitions.  # noqa: E501
        :rtype: str
        """
        return self._ending_before

    @ending_before.setter
    def ending_before(self, ending_before):
        """Sets the ending_before of this BulkTransitionGetAvailableTransitions.

        The end cursor for use in pagination.  # noqa: E501

        :param ending_before: The ending_before of this BulkTransitionGetAvailableTransitions.  # noqa: E501
        :type: str
        """

        self._ending_before = ending_before

    @property
    def starting_after(self):
        """Gets the starting_after of this BulkTransitionGetAvailableTransitions.  # noqa: E501

        The start cursor for use in pagination.  # noqa: E501

        :return: The starting_after of this BulkTransitionGetAvailableTransitions.  # noqa: E501
        :rtype: str
        """
        return self._starting_after

    @starting_after.setter
    def starting_after(self, starting_after):
        """Sets the starting_after of this BulkTransitionGetAvailableTransitions.

        The start cursor for use in pagination.  # noqa: E501

        :param starting_after: The starting_after of this BulkTransitionGetAvailableTransitions.  # noqa: E501
        :type: str
        """

        self._starting_after = starting_after

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BulkTransitionGetAvailableTransitions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BulkTransitionGetAvailableTransitions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
