# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateUiModificationDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contexts': 'list[UiModificationContextDetails]',
        'data': 'str',
        'description': 'str',
        'name': 'str'
    }

    attribute_map = {
        'contexts': 'contexts',
        'data': 'data',
        'description': 'description',
        'name': 'name'
    }

    def __init__(self, contexts=None, data=None, description=None, name=None):  # noqa: E501
        """CreateUiModificationDetails - a model defined in Swagger"""  # noqa: E501
        self._contexts = None
        self._data = None
        self._description = None
        self._name = None
        self.discriminator = None
        if contexts is not None:
            self.contexts = contexts
        if data is not None:
            self.data = data
        if description is not None:
            self.description = description
        self.name = name

    @property
    def contexts(self):
        """Gets the contexts of this CreateUiModificationDetails.  # noqa: E501

        List of contexts of the UI modification. The maximum number of contexts is 1000.  # noqa: E501

        :return: The contexts of this CreateUiModificationDetails.  # noqa: E501
        :rtype: list[UiModificationContextDetails]
        """
        return self._contexts

    @contexts.setter
    def contexts(self, contexts):
        """Sets the contexts of this CreateUiModificationDetails.

        List of contexts of the UI modification. The maximum number of contexts is 1000.  # noqa: E501

        :param contexts: The contexts of this CreateUiModificationDetails.  # noqa: E501
        :type: list[UiModificationContextDetails]
        """

        self._contexts = contexts

    @property
    def data(self):
        """Gets the data of this CreateUiModificationDetails.  # noqa: E501

        The data of the UI modification. The maximum size of the data is 50000 characters.  # noqa: E501

        :return: The data of this CreateUiModificationDetails.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CreateUiModificationDetails.

        The data of the UI modification. The maximum size of the data is 50000 characters.  # noqa: E501

        :param data: The data of this CreateUiModificationDetails.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def description(self):
        """Gets the description of this CreateUiModificationDetails.  # noqa: E501

        The description of the UI modification. The maximum length is 255 characters.  # noqa: E501

        :return: The description of this CreateUiModificationDetails.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateUiModificationDetails.

        The description of the UI modification. The maximum length is 255 characters.  # noqa: E501

        :param description: The description of this CreateUiModificationDetails.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this CreateUiModificationDetails.  # noqa: E501

        The name of the UI modification. The maximum length is 255 characters.  # noqa: E501

        :return: The name of this CreateUiModificationDetails.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateUiModificationDetails.

        The name of the UI modification. The maximum length is 255 characters.  # noqa: E501

        :param name: The name of this CreateUiModificationDetails.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateUiModificationDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateUiModificationDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
