# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FieldConfigurationSchemeProjectAssociation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_configuration_scheme_id': 'str',
        'project_id': 'str'
    }

    attribute_map = {
        'field_configuration_scheme_id': 'fieldConfigurationSchemeId',
        'project_id': 'projectId'
    }

    def __init__(self, field_configuration_scheme_id=None, project_id=None):  # noqa: E501
        """FieldConfigurationSchemeProjectAssociation - a model defined in Swagger"""  # noqa: E501
        self._field_configuration_scheme_id = None
        self._project_id = None
        self.discriminator = None
        if field_configuration_scheme_id is not None:
            self.field_configuration_scheme_id = field_configuration_scheme_id
        self.project_id = project_id

    @property
    def field_configuration_scheme_id(self):
        """Gets the field_configuration_scheme_id of this FieldConfigurationSchemeProjectAssociation.  # noqa: E501

        The ID of the field configuration scheme. If the field configuration scheme ID is `null`, the operation assigns the default field configuration scheme.  # noqa: E501

        :return: The field_configuration_scheme_id of this FieldConfigurationSchemeProjectAssociation.  # noqa: E501
        :rtype: str
        """
        return self._field_configuration_scheme_id

    @field_configuration_scheme_id.setter
    def field_configuration_scheme_id(self, field_configuration_scheme_id):
        """Sets the field_configuration_scheme_id of this FieldConfigurationSchemeProjectAssociation.

        The ID of the field configuration scheme. If the field configuration scheme ID is `null`, the operation assigns the default field configuration scheme.  # noqa: E501

        :param field_configuration_scheme_id: The field_configuration_scheme_id of this FieldConfigurationSchemeProjectAssociation.  # noqa: E501
        :type: str
        """

        self._field_configuration_scheme_id = field_configuration_scheme_id

    @property
    def project_id(self):
        """Gets the project_id of this FieldConfigurationSchemeProjectAssociation.  # noqa: E501

        The ID of the project.  # noqa: E501

        :return: The project_id of this FieldConfigurationSchemeProjectAssociation.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this FieldConfigurationSchemeProjectAssociation.

        The ID of the project.  # noqa: E501

        :param project_id: The project_id of this FieldConfigurationSchemeProjectAssociation.  # noqa: E501
        :type: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldConfigurationSchemeProjectAssociation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldConfigurationSchemeProjectAssociation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
