# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Group(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expand': 'str',
        'group_id': 'str',
        'name': 'str',
        '_self': 'str',
        'users': 'AllOfGroupUsers'
    }

    attribute_map = {
        'expand': 'expand',
        'group_id': 'groupId',
        'name': 'name',
        '_self': 'self',
        'users': 'users'
    }

    def __init__(self, expand=None, group_id=None, name=None, _self=None, users=None):  # noqa: E501
        """Group - a model defined in Swagger"""  # noqa: E501
        self._expand = None
        self._group_id = None
        self._name = None
        self.__self = None
        self._users = None
        self.discriminator = None
        if expand is not None:
            self.expand = expand
        if group_id is not None:
            self.group_id = group_id
        if name is not None:
            self.name = name
        if _self is not None:
            self._self = _self
        if users is not None:
            self.users = users

    @property
    def expand(self):
        """Gets the expand of this Group.  # noqa: E501

        Expand options that include additional group details in the response.  # noqa: E501

        :return: The expand of this Group.  # noqa: E501
        :rtype: str
        """
        return self._expand

    @expand.setter
    def expand(self, expand):
        """Sets the expand of this Group.

        Expand options that include additional group details in the response.  # noqa: E501

        :param expand: The expand of this Group.  # noqa: E501
        :type: str
        """

        self._expand = expand

    @property
    def group_id(self):
        """Gets the group_id of this Group.  # noqa: E501

        The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*.  # noqa: E501

        :return: The group_id of this Group.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this Group.

        The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*.  # noqa: E501

        :param group_id: The group_id of this Group.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def name(self):
        """Gets the name of this Group.  # noqa: E501

        The name of group.  # noqa: E501

        :return: The name of this Group.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Group.

        The name of group.  # noqa: E501

        :param name: The name of this Group.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def _self(self):
        """Gets the _self of this Group.  # noqa: E501

        The URL for these group details.  # noqa: E501

        :return: The _self of this Group.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this Group.

        The URL for these group details.  # noqa: E501

        :param _self: The _self of this Group.  # noqa: E501
        :type: str
        """

        self.__self = _self

    @property
    def users(self):
        """Gets the users of this Group.  # noqa: E501

        A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append `[start-index:end-index]` to the expand request. For example, to access the next 50 users, use`?expand=users[51:100]`.  # noqa: E501

        :return: The users of this Group.  # noqa: E501
        :rtype: AllOfGroupUsers
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this Group.

        A paginated list of the users that are members of the group. A maximum of 50 users is returned in the list, to access additional users append `[start-index:end-index]` to the expand request. For example, to access the next 50 users, use`?expand=users[51:100]`.  # noqa: E501

        :param users: The users of this Group.  # noqa: E501
        :type: AllOfGroupUsers
        """

        self._users = users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Group, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Group):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
