# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IconBean(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'link': 'str',
        'title': 'str',
        'url16x16': 'str'
    }

    attribute_map = {
        'link': 'link',
        'title': 'title',
        'url16x16': 'url16x16'
    }

    def __init__(self, link=None, title=None, url16x16=None):  # noqa: E501
        """IconBean - a model defined in Swagger"""  # noqa: E501
        self._link = None
        self._title = None
        self._url16x16 = None
        self.discriminator = None
        if link is not None:
            self.link = link
        if title is not None:
            self.title = title
        if url16x16 is not None:
            self.url16x16 = url16x16

    @property
    def link(self):
        """Gets the link of this IconBean.  # noqa: E501

        The URL of the tooltip, used only for a status icon.  # noqa: E501

        :return: The link of this IconBean.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this IconBean.

        The URL of the tooltip, used only for a status icon.  # noqa: E501

        :param link: The link of this IconBean.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def title(self):
        """Gets the title of this IconBean.  # noqa: E501

        The title of the icon, for use as a tooltip on the icon.  # noqa: E501

        :return: The title of this IconBean.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this IconBean.

        The title of the icon, for use as a tooltip on the icon.  # noqa: E501

        :param title: The title of this IconBean.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def url16x16(self):
        """Gets the url16x16 of this IconBean.  # noqa: E501

        The URL of a 16x16 pixel icon.  # noqa: E501

        :return: The url16x16 of this IconBean.  # noqa: E501
        :rtype: str
        """
        return self._url16x16

    @url16x16.setter
    def url16x16(self, url16x16):
        """Sets the url16x16 of this IconBean.

        The URL of a 16x16 pixel icon.  # noqa: E501

        :param url16x16: The url16x16 of this IconBean.  # noqa: E501
        :type: str
        """

        self._url16x16 = url16x16

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IconBean, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IconBean):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
