# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IssueTypeProjectCreatePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'issue_type_hierarchy': 'list[IssueTypeHierarchyPayload]',
        'issue_type_scheme': 'IssueTypeSchemePayload',
        'issue_types': 'list[IssueTypePayload]'
    }

    attribute_map = {
        'issue_type_hierarchy': 'issueTypeHierarchy',
        'issue_type_scheme': 'issueTypeScheme',
        'issue_types': 'issueTypes'
    }

    def __init__(self, issue_type_hierarchy=None, issue_type_scheme=None, issue_types=None):  # noqa: E501
        """IssueTypeProjectCreatePayload - a model defined in Swagger"""  # noqa: E501
        self._issue_type_hierarchy = None
        self._issue_type_scheme = None
        self._issue_types = None
        self.discriminator = None
        if issue_type_hierarchy is not None:
            self.issue_type_hierarchy = issue_type_hierarchy
        if issue_type_scheme is not None:
            self.issue_type_scheme = issue_type_scheme
        if issue_types is not None:
            self.issue_types = issue_types

    @property
    def issue_type_hierarchy(self):
        """Gets the issue_type_hierarchy of this IssueTypeProjectCreatePayload.  # noqa: E501

        Defines the issue type hierarhy to be created and used during this project creation. This will only add new levels if there isn't an existing level  # noqa: E501

        :return: The issue_type_hierarchy of this IssueTypeProjectCreatePayload.  # noqa: E501
        :rtype: list[IssueTypeHierarchyPayload]
        """
        return self._issue_type_hierarchy

    @issue_type_hierarchy.setter
    def issue_type_hierarchy(self, issue_type_hierarchy):
        """Sets the issue_type_hierarchy of this IssueTypeProjectCreatePayload.

        Defines the issue type hierarhy to be created and used during this project creation. This will only add new levels if there isn't an existing level  # noqa: E501

        :param issue_type_hierarchy: The issue_type_hierarchy of this IssueTypeProjectCreatePayload.  # noqa: E501
        :type: list[IssueTypeHierarchyPayload]
        """

        self._issue_type_hierarchy = issue_type_hierarchy

    @property
    def issue_type_scheme(self):
        """Gets the issue_type_scheme of this IssueTypeProjectCreatePayload.  # noqa: E501


        :return: The issue_type_scheme of this IssueTypeProjectCreatePayload.  # noqa: E501
        :rtype: IssueTypeSchemePayload
        """
        return self._issue_type_scheme

    @issue_type_scheme.setter
    def issue_type_scheme(self, issue_type_scheme):
        """Sets the issue_type_scheme of this IssueTypeProjectCreatePayload.


        :param issue_type_scheme: The issue_type_scheme of this IssueTypeProjectCreatePayload.  # noqa: E501
        :type: IssueTypeSchemePayload
        """

        self._issue_type_scheme = issue_type_scheme

    @property
    def issue_types(self):
        """Gets the issue_types of this IssueTypeProjectCreatePayload.  # noqa: E501

        Only needed if you want to create issue types, you can otherwise use the ids of issue types in the scheme configuration  # noqa: E501

        :return: The issue_types of this IssueTypeProjectCreatePayload.  # noqa: E501
        :rtype: list[IssueTypePayload]
        """
        return self._issue_types

    @issue_types.setter
    def issue_types(self, issue_types):
        """Sets the issue_types of this IssueTypeProjectCreatePayload.

        Only needed if you want to create issue types, you can otherwise use the ids of issue types in the scheme configuration  # noqa: E501

        :param issue_types: The issue_types of this IssueTypeProjectCreatePayload.  # noqa: E501
        :type: list[IssueTypePayload]
        """

        self._issue_types = issue_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IssueTypeProjectCreatePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IssueTypeProjectCreatePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
