# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IssueLayoutItemPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_key': 'ProjectCreateResourceIdentifier',
        'section_type': 'str',
        'type': 'str'
    }

    attribute_map = {
        'item_key': 'itemKey',
        'section_type': 'sectionType',
        'type': 'type'
    }

    def __init__(self, item_key=None, section_type=None, type=None):  # noqa: E501
        """IssueLayoutItemPayload - a model defined in Swagger"""  # noqa: E501
        self._item_key = None
        self._section_type = None
        self._type = None
        self.discriminator = None
        if item_key is not None:
            self.item_key = item_key
        if section_type is not None:
            self.section_type = section_type
        if type is not None:
            self.type = type

    @property
    def item_key(self):
        """Gets the item_key of this IssueLayoutItemPayload.  # noqa: E501


        :return: The item_key of this IssueLayoutItemPayload.  # noqa: E501
        :rtype: ProjectCreateResourceIdentifier
        """
        return self._item_key

    @item_key.setter
    def item_key(self, item_key):
        """Sets the item_key of this IssueLayoutItemPayload.


        :param item_key: The item_key of this IssueLayoutItemPayload.  # noqa: E501
        :type: ProjectCreateResourceIdentifier
        """

        self._item_key = item_key

    @property
    def section_type(self):
        """Gets the section_type of this IssueLayoutItemPayload.  # noqa: E501

        The item section type  # noqa: E501

        :return: The section_type of this IssueLayoutItemPayload.  # noqa: E501
        :rtype: str
        """
        return self._section_type

    @section_type.setter
    def section_type(self, section_type):
        """Sets the section_type of this IssueLayoutItemPayload.

        The item section type  # noqa: E501

        :param section_type: The section_type of this IssueLayoutItemPayload.  # noqa: E501
        :type: str
        """
        allowed_values = ["content", "primaryContext", "secondaryContext"]  # noqa: E501
        if section_type not in allowed_values:
            raise ValueError(
                "Invalid value for `section_type` ({0}), must be one of {1}"  # noqa: E501
                .format(section_type, allowed_values)
            )

        self._section_type = section_type

    @property
    def type(self):
        """Gets the type of this IssueLayoutItemPayload.  # noqa: E501

        The item type. Currently only support FIELD  # noqa: E501

        :return: The type of this IssueLayoutItemPayload.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this IssueLayoutItemPayload.

        The item type. Currently only support FIELD  # noqa: E501

        :param type: The type of this IssueLayoutItemPayload.  # noqa: E501
        :type: str
        """
        allowed_values = ["FIELD"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IssueLayoutItemPayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IssueLayoutItemPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
