# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JiraExpressionForAnalysis(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context_variables': 'dict(str, str)',
        'expressions': 'list[str]'
    }

    attribute_map = {
        'context_variables': 'contextVariables',
        'expressions': 'expressions'
    }

    def __init__(self, context_variables=None, expressions=None):  # noqa: E501
        """JiraExpressionForAnalysis - a model defined in Swagger"""  # noqa: E501
        self._context_variables = None
        self._expressions = None
        self.discriminator = None
        if context_variables is not None:
            self.context_variables = context_variables
        self.expressions = expressions

    @property
    def context_variables(self):
        """Gets the context_variables of this JiraExpressionForAnalysis.  # noqa: E501

        Context variables and their types. The type checker assumes that [common context variables](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/#context-variables), such as `issue` or `project`, are available in context and sets their type. Use this property to override the default types or provide details of new variables.  # noqa: E501

        :return: The context_variables of this JiraExpressionForAnalysis.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._context_variables

    @context_variables.setter
    def context_variables(self, context_variables):
        """Sets the context_variables of this JiraExpressionForAnalysis.

        Context variables and their types. The type checker assumes that [common context variables](https://developer.atlassian.com/cloud/jira/platform/jira-expressions/#context-variables), such as `issue` or `project`, are available in context and sets their type. Use this property to override the default types or provide details of new variables.  # noqa: E501

        :param context_variables: The context_variables of this JiraExpressionForAnalysis.  # noqa: E501
        :type: dict(str, str)
        """

        self._context_variables = context_variables

    @property
    def expressions(self):
        """Gets the expressions of this JiraExpressionForAnalysis.  # noqa: E501

        The list of Jira expressions to analyse.  # noqa: E501

        :return: The expressions of this JiraExpressionForAnalysis.  # noqa: E501
        :rtype: list[str]
        """
        return self._expressions

    @expressions.setter
    def expressions(self, expressions):
        """Sets the expressions of this JiraExpressionForAnalysis.

        The list of Jira expressions to analyse.  # noqa: E501

        :param expressions: The expressions of this JiraExpressionForAnalysis.  # noqa: E501
        :type: list[str]
        """
        if expressions is None:
            raise ValueError("Invalid value for `expressions`, must not be `None`")  # noqa: E501

        self._expressions = expressions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JiraExpressionForAnalysis, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JiraExpressionForAnalysis):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
