# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JiraRichTextInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adf_value': 'dict(str, object)'
    }

    attribute_map = {
        'adf_value': 'adfValue'
    }

    def __init__(self, adf_value=None):  # noqa: E501
        """JiraRichTextInput - a model defined in Swagger"""  # noqa: E501
        self._adf_value = None
        self.discriminator = None
        if adf_value is not None:
            self.adf_value = adf_value

    @property
    def adf_value(self):
        """Gets the adf_value of this JiraRichTextInput.  # noqa: E501


        :return: The adf_value of this JiraRichTextInput.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._adf_value

    @adf_value.setter
    def adf_value(self, adf_value):
        """Sets the adf_value of this JiraRichTextInput.


        :param adf_value: The adf_value of this JiraRichTextInput.  # noqa: E501
        :type: dict(str, object)
        """

        self._adf_value = adf_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JiraRichTextInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JiraRichTextInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
