# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PaginatedResponseComment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max_results': 'int',
        'results': 'list[Comment]',
        'start_at': 'int',
        'total': 'int'
    }

    attribute_map = {
        'max_results': 'maxResults',
        'results': 'results',
        'start_at': 'startAt',
        'total': 'total'
    }

    def __init__(self, max_results=None, results=None, start_at=None, total=None):  # noqa: E501
        """PaginatedResponseComment - a model defined in Swagger"""  # noqa: E501
        self._max_results = None
        self._results = None
        self._start_at = None
        self._total = None
        self.discriminator = None
        if max_results is not None:
            self.max_results = max_results
        if results is not None:
            self.results = results
        if start_at is not None:
            self.start_at = start_at
        if total is not None:
            self.total = total

    @property
    def max_results(self):
        """Gets the max_results of this PaginatedResponseComment.  # noqa: E501


        :return: The max_results of this PaginatedResponseComment.  # noqa: E501
        :rtype: int
        """
        return self._max_results

    @max_results.setter
    def max_results(self, max_results):
        """Sets the max_results of this PaginatedResponseComment.


        :param max_results: The max_results of this PaginatedResponseComment.  # noqa: E501
        :type: int
        """

        self._max_results = max_results

    @property
    def results(self):
        """Gets the results of this PaginatedResponseComment.  # noqa: E501


        :return: The results of this PaginatedResponseComment.  # noqa: E501
        :rtype: list[Comment]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this PaginatedResponseComment.


        :param results: The results of this PaginatedResponseComment.  # noqa: E501
        :type: list[Comment]
        """

        self._results = results

    @property
    def start_at(self):
        """Gets the start_at of this PaginatedResponseComment.  # noqa: E501


        :return: The start_at of this PaginatedResponseComment.  # noqa: E501
        :rtype: int
        """
        return self._start_at

    @start_at.setter
    def start_at(self, start_at):
        """Sets the start_at of this PaginatedResponseComment.


        :param start_at: The start_at of this PaginatedResponseComment.  # noqa: E501
        :type: int
        """

        self._start_at = start_at

    @property
    def total(self):
        """Gets the total of this PaginatedResponseComment.  # noqa: E501


        :return: The total of this PaginatedResponseComment.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this PaginatedResponseComment.


        :param total: The total of this PaginatedResponseComment.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaginatedResponseComment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaginatedResponseComment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
