# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RolePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_actors': 'list[ProjectCreateResourceIdentifier]',
        'description': 'str',
        'name': 'str',
        'on_conflict': 'str',
        'pcri': 'ProjectCreateResourceIdentifier',
        'type': 'str'
    }

    attribute_map = {
        'default_actors': 'defaultActors',
        'description': 'description',
        'name': 'name',
        'on_conflict': 'onConflict',
        'pcri': 'pcri',
        'type': 'type'
    }

    def __init__(self, default_actors=None, description=None, name=None, on_conflict='USE', pcri=None, type=None):  # noqa: E501
        """RolePayload - a model defined in Swagger"""  # noqa: E501
        self._default_actors = None
        self._description = None
        self._name = None
        self._on_conflict = None
        self._pcri = None
        self._type = None
        self.discriminator = None
        if default_actors is not None:
            self.default_actors = default_actors
        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if on_conflict is not None:
            self.on_conflict = on_conflict
        if pcri is not None:
            self.pcri = pcri
        if type is not None:
            self.type = type

    @property
    def default_actors(self):
        """Gets the default_actors of this RolePayload.  # noqa: E501

        The default actors for the role. By adding default actors, the role will be added to any future projects created  # noqa: E501

        :return: The default_actors of this RolePayload.  # noqa: E501
        :rtype: list[ProjectCreateResourceIdentifier]
        """
        return self._default_actors

    @default_actors.setter
    def default_actors(self, default_actors):
        """Sets the default_actors of this RolePayload.

        The default actors for the role. By adding default actors, the role will be added to any future projects created  # noqa: E501

        :param default_actors: The default_actors of this RolePayload.  # noqa: E501
        :type: list[ProjectCreateResourceIdentifier]
        """

        self._default_actors = default_actors

    @property
    def description(self):
        """Gets the description of this RolePayload.  # noqa: E501

        The description of the role  # noqa: E501

        :return: The description of this RolePayload.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this RolePayload.

        The description of the role  # noqa: E501

        :param description: The description of this RolePayload.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this RolePayload.  # noqa: E501

        The name of the role  # noqa: E501

        :return: The name of this RolePayload.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RolePayload.

        The name of the role  # noqa: E501

        :param name: The name of this RolePayload.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def on_conflict(self):
        """Gets the on_conflict of this RolePayload.  # noqa: E501

        The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters  # noqa: E501

        :return: The on_conflict of this RolePayload.  # noqa: E501
        :rtype: str
        """
        return self._on_conflict

    @on_conflict.setter
    def on_conflict(self, on_conflict):
        """Sets the on_conflict of this RolePayload.

        The strategy to use when there is a conflict with an existing project role. FAIL - Fail execution, this always needs to be unique; USE - Use the existing entity and ignore new entity parameters  # noqa: E501

        :param on_conflict: The on_conflict of this RolePayload.  # noqa: E501
        :type: str
        """
        allowed_values = ["FAIL", "USE", "NEW"]  # noqa: E501
        if on_conflict not in allowed_values:
            raise ValueError(
                "Invalid value for `on_conflict` ({0}), must be one of {1}"  # noqa: E501
                .format(on_conflict, allowed_values)
            )

        self._on_conflict = on_conflict

    @property
    def pcri(self):
        """Gets the pcri of this RolePayload.  # noqa: E501


        :return: The pcri of this RolePayload.  # noqa: E501
        :rtype: ProjectCreateResourceIdentifier
        """
        return self._pcri

    @pcri.setter
    def pcri(self, pcri):
        """Sets the pcri of this RolePayload.


        :param pcri: The pcri of this RolePayload.  # noqa: E501
        :type: ProjectCreateResourceIdentifier
        """

        self._pcri = pcri

    @property
    def type(self):
        """Gets the type of this RolePayload.  # noqa: E501

        The type of the role. Only used by project-scoped project  # noqa: E501

        :return: The type of this RolePayload.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RolePayload.

        The type of the role. Only used by project-scoped project  # noqa: E501

        :param type: The type of this RolePayload.  # noqa: E501
        :type: str
        """
        allowed_values = ["HIDDEN", "VIEWABLE", "EDITABLE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RolePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RolePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
