# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RuleConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disabled': 'bool',
        'tag': 'str',
        'value': 'str'
    }

    attribute_map = {
        'disabled': 'disabled',
        'tag': 'tag',
        'value': 'value'
    }

    def __init__(self, disabled=False, tag=None, value=None):  # noqa: E501
        """RuleConfiguration - a model defined in Swagger"""  # noqa: E501
        self._disabled = None
        self._tag = None
        self._value = None
        self.discriminator = None
        if disabled is not None:
            self.disabled = disabled
        if tag is not None:
            self.tag = tag
        self.value = value

    @property
    def disabled(self):
        """Gets the disabled of this RuleConfiguration.  # noqa: E501

        Whether the rule is disabled.  # noqa: E501

        :return: The disabled of this RuleConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this RuleConfiguration.

        Whether the rule is disabled.  # noqa: E501

        :param disabled: The disabled of this RuleConfiguration.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def tag(self):
        """Gets the tag of this RuleConfiguration.  # noqa: E501

        A tag used to filter rules in [Get workflow transition rule configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get).  # noqa: E501

        :return: The tag of this RuleConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this RuleConfiguration.

        A tag used to filter rules in [Get workflow transition rule configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get).  # noqa: E501

        :param tag: The tag of this RuleConfiguration.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def value(self):
        """Gets the value of this RuleConfiguration.  # noqa: E501

        Configuration of the rule, as it is stored by the Connect or the Forge app on the rule configuration page.  # noqa: E501

        :return: The value of this RuleConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RuleConfiguration.

        Configuration of the rule, as it is stored by the Connect or the Forge app on the rule configuration page.  # noqa: E501

        :param value: The value of this RuleConfiguration.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RuleConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuleConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
