# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatusMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        'id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'category': 'category',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, category=None, id=None, name=None):  # noqa: E501
        """StatusMetadata - a model defined in Swagger"""  # noqa: E501
        self._category = None
        self._id = None
        self._name = None
        self.discriminator = None
        if category is not None:
            self.category = category
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name

    @property
    def category(self):
        """Gets the category of this StatusMetadata.  # noqa: E501

        The category of the status.  # noqa: E501

        :return: The category of this StatusMetadata.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this StatusMetadata.

        The category of the status.  # noqa: E501

        :param category: The category of this StatusMetadata.  # noqa: E501
        :type: str
        """
        allowed_values = ["TODO", "IN_PROGRESS", "DONE"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"  # noqa: E501
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def id(self):
        """Gets the id of this StatusMetadata.  # noqa: E501

        The ID of the status.  # noqa: E501

        :return: The id of this StatusMetadata.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StatusMetadata.

        The ID of the status.  # noqa: E501

        :param id: The id of this StatusMetadata.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this StatusMetadata.  # noqa: E501

        The name of the status.  # noqa: E501

        :return: The name of this StatusMetadata.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StatusMetadata.

        The name of the status.  # noqa: E501

        :param name: The name of this StatusMetadata.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatusMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatusMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
