# coding: utf-8

"""
    The Jira Cloud platform REST API

    Jira Cloud platform REST API documentation  # noqa: E501

    OpenAPI spec version: 1001.0.0-SNAPSHOT-0daa9a9e2722e510da52cb72ee41a43128c97f42
    Contact: ecosystem@atlassian.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkflowCreateValidateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payload': 'WorkflowCreateRequest',
        'validation_options': 'ValidationOptionsForCreate'
    }

    attribute_map = {
        'payload': 'payload',
        'validation_options': 'validationOptions'
    }

    def __init__(self, payload=None, validation_options=None):  # noqa: E501
        """WorkflowCreateValidateRequest - a model defined in Swagger"""  # noqa: E501
        self._payload = None
        self._validation_options = None
        self.discriminator = None
        self.payload = payload
        if validation_options is not None:
            self.validation_options = validation_options

    @property
    def payload(self):
        """Gets the payload of this WorkflowCreateValidateRequest.  # noqa: E501


        :return: The payload of this WorkflowCreateValidateRequest.  # noqa: E501
        :rtype: WorkflowCreateRequest
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this WorkflowCreateValidateRequest.


        :param payload: The payload of this WorkflowCreateValidateRequest.  # noqa: E501
        :type: WorkflowCreateRequest
        """
        if payload is None:
            raise ValueError("Invalid value for `payload`, must not be `None`")  # noqa: E501

        self._payload = payload

    @property
    def validation_options(self):
        """Gets the validation_options of this WorkflowCreateValidateRequest.  # noqa: E501


        :return: The validation_options of this WorkflowCreateValidateRequest.  # noqa: E501
        :rtype: ValidationOptionsForCreate
        """
        return self._validation_options

    @validation_options.setter
    def validation_options(self, validation_options):
        """Sets the validation_options of this WorkflowCreateValidateRequest.


        :param validation_options: The validation_options of this WorkflowCreateValidateRequest.  # noqa: E501
        :type: ValidationOptionsForCreate
        """

        self._validation_options = validation_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowCreateValidateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowCreateValidateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
